version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=damagewizdb
      - MYSQL_ROOT_PASSWORD=134679258
    volumes:
      - db:/var/lib/mysql
    network_mode: "host"

  svc:
    build: ../damagewiz-web
    depends_on:
      - db
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/damagewizdb
    network_mode: "host"
    command: "--server.port=8082"

volumes:
  db:
    driver: local

