version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=damagewizdb
      - MYSQL_ROOT_PASSWORD=134679258
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  svc:
    build: ./damagewiz-web
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/damagewizdb
  cors-proxy:
    build: ./cors-proxy
    ports:
      - "9090:9090"
    depends_on:
      - svc
      - db

volumes:
  db:
    driver: local

